#!/bin/bash

ALLREPOS_MYDIR=$(dirname ${BASH_SOURCE[0]})
. ${ALLREPOS_MYDIR}/common.sh

$ALLREPOS_MYDIR/all_repos | parallel --tag --jobs $ALLREPOS_CONCURRENCY -- 'cd {}
git fetch --all
if [[ changes -gt 0 ]]; then
  print_changes
else
  git pull
fi
'