#!/bin/bash

ALLREPOS_MYDIR=$(dirname ${BASH_SOURCE[0]})
. ${ALLREPOS_MYDIR}/common.sh

$ALLREPOS_MYDIR/all_repos | parallel --tag --progress --bar -- 'cd {}
git fetch --all
CHANGES=$(git status --porcelain | wc -l)
if [ $CHANGES -gt 0 ]; then
  printf "\n\e[33;1mChanges in {}\n"
  git status --porcelain
  printf "\e[0m"
else
  git pull
fi
'